/**
 * Blacklist Form Component
 *
 * Shared form component for creating and editing blacklist entries
 */

import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Button } from '@/components/ui/button';
import { RefreshCw } from 'lucide-react';
import type {
  InboundBlacklistMatchType,
  InboundBlacklistRejectionStrategy,
  DIDNumber,
} from '@/types';

interface FormData {
  caller_id_pattern: string;
  match_type: InboundBlacklistMatchType;
  rejection_strategy: InboundBlacklistRejectionStrategy;
  did_number_ids: string[];
  is_global: boolean;
  // Note: torment_room_prefix and torment_music_timeout are auto-generated by backend
}

interface BlacklistFormProps {
  formData: FormData;
  formErrors: Partial<Record<keyof FormData, string>>;
  phoneNumbers: DIDNumber[];
  onChange: (data: FormData) => void;
  onToggleDid: (didId: string) => void;
  onRefreshPhoneNumbers: () => void;
}

export function BlacklistForm({
  formData,
  formErrors,
  phoneNumbers,
  onChange,
  onToggleDid,
  onRefreshPhoneNumbers,
}: BlacklistFormProps) {
  return (
    <div className="space-y-4 py-4">
      <div>
        <Label htmlFor="caller_id_pattern">Caller ID Pattern</Label>
        <Input
          id="caller_id_pattern"
          value={formData.caller_id_pattern}
          onChange={(e) => onChange({ ...formData, caller_id_pattern: e.target.value })}
          placeholder="+14155551234 or +1415*"
          required
        />
        <p className="text-xs text-muted-foreground mt-1">
          E.164 format. Use * for wildcards (e.g., +1415* blocks all SF numbers)
        </p>
        {formErrors.caller_id_pattern && (
          <p className="text-sm text-destructive mt-1">{formErrors.caller_id_pattern}</p>
        )}
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div>
          <Label htmlFor="match_type">Match Type</Label>
          <Select
            value={formData.match_type}
            onValueChange={(value: InboundBlacklistMatchType) =>
              onChange({ ...formData, match_type: value })
            }
          >
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="exact">Exact Match</SelectItem>
              <SelectItem value="prefix">Prefix Match</SelectItem>
              <SelectItem value="wildcard">Wildcard Pattern</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <div>
          <Label htmlFor="rejection_strategy">Rejection Strategy</Label>
          <Select
            value={formData.rejection_strategy}
            onValueChange={(value: InboundBlacklistRejectionStrategy) =>
              onChange({ ...formData, rejection_strategy: value })
            }
          >
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="drop">Drop (Silent)</SelectItem>
              <SelectItem value="reject">Reject (Message)</SelectItem>
              <SelectItem value="torment">Torment (Music)</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      {formData.rejection_strategy === 'torment' && (
        <div className="p-4 bg-purple-50 rounded-lg">
          <p className="text-sm text-purple-800">
            <strong>Torment Mode:</strong> Blocked callers will be placed in a
            holding room with music for 10 minutes (600 seconds) before being
            disconnected. Room prefix is auto-generated.
          </p>
        </div>
      )}

      <div className="border-t pt-4 space-y-4">
        <div className="flex items-center justify-between">
          <div className="space-y-0.5">
            <Label>Global Blacklist</Label>
            <p className="text-xs text-muted-foreground">
              Apply to all phone numbers in your organization
            </p>
          </div>
          <Switch
            checked={formData.is_global}
            onCheckedChange={(checked) =>
              onChange({
                ...formData,
                is_global: checked,
                did_number_ids: checked ? [] : formData.did_number_ids,
              })
            }
          />
        </div>

        {!formData.is_global && (
          <div>
            <Label>Select Phone Numbers</Label>
            <div className="border rounded-md p-2 mt-1 max-h-40 overflow-y-auto">
              {phoneNumbers.length === 0 ? (
                <p className="text-sm text-muted-foreground py-2">
                  No phone numbers available
                </p>
              ) : (
                phoneNumbers.map((did: DIDNumber) => (
                  <label
                    key={did.id}
                    className="flex items-center gap-2 p-2 hover:bg-muted rounded cursor-pointer"
                  >
                    <input
                      type="checkbox"
                      checked={formData.did_number_ids.includes(did.id)}
                      onChange={() => onToggleDid(did.id)}
                      className="rounded border-gray-300"
                    />
                    <span className="text-sm">
                      {did.friendly_name || did.phone_number}
                    </span>
                  </label>
                ))
              )}
            </div>
            <div className="flex items-center justify-between mt-2">
              <span className="text-xs text-muted-foreground">
                {formData.did_number_ids.length} selected
              </span>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={onRefreshPhoneNumbers}
              >
                <RefreshCw className="h-3 w-3 mr-1" />
                Refresh
              </Button>
            </div>
            {formErrors.did_number_ids && (
              <p className="text-sm text-destructive mt-1">
                {formErrors.did_number_ids}
              </p>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export default BlacklistForm;
